services:
  dream-league-web:
    extends:
      file: compose.yaml
      service: dream-league-web
    build:
      target: development
    image: dream-league-web-zap
    volumes:
      - ./test-output:/home/node/test-output

  dream-league-web-zap:
    image: softwaresecurityproject/zap-bare:2.14.0
    command: zap.sh -cmd -quickurl http://dream-league-web:${PORT:-3000} -configfile wrk/config/zap.conf -quickout wrk/test-output/zap-report.html
    depends_on:
      - dream-league-web
    volumes:
      - ./test-output:/zap/wrk/test-output
      - ./zap:/zap/wrk/config
