version: '3.7'
services:
  dream-league-web:
    build:
      context: .
      target: development
    ports:
      - "3003:3003"
      - "9232:9229"
    environment:
      JWT_SECRET: secret
      API_GATEWAY_HOST: http://dream-league-api-gateway:3001
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
