version: '3.7'
services:
  dream-league-web:
    build:
      context: .
      target: development
    ports:
      - "3001:3001"
      - "9230:9229"
    environment:
      JWT_SECRET: secret
      API_HOST: http://dream-league-api:3000
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
