version: '3.7'
services:
  dream-league-web:
    build:
      context: .
      target: development
    command: >
      sh -c "
        chmod -R 777 test/files &&
        npm run test"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
      - ./test/:/home/node/test/
      - ./test-output/:/home/node/test-output/      
