version: '3.8'
services:
  dream-league-web:
    build:
      context: .
      target: development
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./package.json:/home/node/package.json
