services:
  dream-league-web:
    build:
      target: development
    image: dream-league-web-zap
    volumes:
      - ./test-output:/home/node/test-output

  dream-league-web-zap:
    image: owasp/zap2docker-stable:2.12.0
    command: zap-baseline.py -t http://dream-league-web:${PORT:-3000} -c config/zap.conf -r test-output/zap-report.html -a -d -I
    depends_on:
      - dream-league-web
    volumes:
      - ./test-output:/zap/wrk/test-output
      - ./zap:/zap/wrk/config
