apiVersion: v2
name: dream-league-web
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
dependencies:
- name: helm-library
  version: ^2.7.3
  repository: https://helm.lynxmagnus.com
