environment: production
name: dream-league-web
image: dream-league-web

container:
  resourceTier: M
  port: 3000

config:
  apiHost: http://dream-league-api

secret:
  secretsPath: /dream-league-web

deployment: {}

ingress:
  host: dreamleaguefantasyfootball.co.uk

