environment: development
name: dream-league-web
image: dream-league-web

container:
  imagePullPolicy: Always
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 300Mi
  limitCpu: 300m
  port: 3000
  jwtSecret: secret
  apiHost: http://dream-league-api

deployment:
  restartPolicy: Always
  replicas: 1
  minReadySeconds: 0

ingress:
  class: nginx
  host:
  certIssuer: letsencrypt

service:
  port: 80
