container:
  image: dream-league-web
  resourceTier: M
  port: 3000

configMap:
  environment: production
  apiHost: http://dream-league-api

secret:
  secretsPath: /dream-league-web

deployment: {}

ingress:
  host: dreamleaguefantasyfootball.co.uk

