environment: production
name: dream-league-web
image: dream-league-web

container:
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 300Mi
  limitCpu: 300m
  port: 3000
  jwtSecret: secret
  apiHost: http://dream-league-api

deployment: {}

ingress: {}

