environment: development
name: dream-league-web
image: dream-league-web

container:
  imagePullPolicy: Always
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  jwtSecret: secret
  apiHost: http://dream-league-api

deployment:
  restartPolicy: Always
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000

ingress:
  class: nginx
  host:
  certIssuer: letsencrypt

service:
  port: 80
