{{- include "helm-library.configmap" (list . "dream-league-web.configmap") -}}
{{- define "dream-league-web.configmap" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  API_HOST: {{ quote .Values.config.apiHost }}
{{- end -}}
