{{- include "helm-library.ingress" (list . "dream-league-web.ingress") -}}
{{- define "dream-league-web.ingress" -}}
metadata:
  annotations:
  {{- if .Values.ingress.host }}    
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "affinity"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
  {{- end }}
{{- end -}}
