#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

service="dream-league-web"

show_help() {
  echo "
    Usage: scripts/test [OPTION...]
    Run tests.

    Options:
      -w, --watch   watch tests
      -h, --help    display this help text
    "
}

while :; do
  case $1 in
    -w|--watch)
      watch="true"
      ;;

    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

compose() {
  if [ "${watch}" != "true" ]; then
    docker-compose -f docker-compose.yaml -f docker-compose.test.yaml -p "${service}-test" $@
  else
    docker-compose -f docker-compose.yaml -f docker-compose.test.yaml -f docker-compose.test.watch.yaml -p "${service}-test" $@
  fi
}

(
  cd "${projectRoot}"

  # Guarantee clean environment
  compose down -v

  # Ensure container images are up to date
  compose build

  # Run tests
  compose run ${service} ${command}

  # Clean up
  compose down -v
)
